### ISSUE TITLE
Ambiguous error for async pragma

### ISSUE THREAD

**Issue by jfilby** [status-im/nim-websock#124]
I'm trying to use nim-websock, but I get a compilation error:

```
Error: ambiguous call; both asyncdispatch.async(prc: untyped) [macro declared in ...\.choosenim\toolchains\nim-1.6.6\lib\pure\asyncmacro.nim(253, 7)]
and asyncloop.async(prc: untyped) [macro declared in ...\.nimble\pkgs\chronos-3.0.6\chronos\asyncmacro2.nim(393, 7)] match for: ()
```

This is from simply adding an {.async.} pragma to the proc that will call this library's Websocket procs.

**Comment by arnetheduck** [comment]
It looks like the module in which you're trying to use websock imports both `asyncdispatch` and `websock` - `websock` is based on `chronos` which replaces and extends `asyncdispatch` - you cannot use both at the same time.
