### ISSUE TITLE
new name for nim-ws

### ISSUE THREAD

**Issue by jangko** [status-im/nim-websock#74]
Because of rejection from nimble packages repo, nim-ws need a new name.
Other reasons are package publicity and visibility.

so far we have one candidate: websock for the package name and nim-websock for repo name.

if no new challenger in the next few days, we will execute this idea.

**Comment by jangko** [comment]
Experimental logo

<img alt="Websock Logo" align="left" src="https://gist.githubusercontent.com/jangko/ef143aa134d27d875964e5aba8c9528e/raw/286c3085586314a8200612d7ca0ac129cea1c16f/websock.svg" width="15%" />

# Websocket for Nim

![Github action](https://github.com/status-im/nim-ws/workflows/nim-ws%20CI/badge.svg)

This is an implementation of [Websocket](https://tools.ietf.org/html/rfc6455) protocol for [Nim](https://nim-lang.org/).

**Comment by dryajov** [comment]
I'd love to see a real spider web 🕸️ in the logo ;)

**Comment by jangko** [comment]
Feel free to edit the svg logo. I'm not good at all when dealing with icons or logos.

**Comment by jangko** [comment]
fixed by #77, closing.
