### ISSUE TITLE
client bug: make clear distinction between host address and host name

### ISSUE THREAD

**Issue by jangko** [status-im/nim-websock#80]
so far we only test the client using ip address and not using actual host name and then resolve it into address. this become a serious bug when connecting to a real server.

see status-im/nim-json-rpc#109.

example uri: "wss://mainnet.infura.io/ws/v3/infura-id"
host name: "mainnet.infura.io" should be sent to server using "Host" field in HTTP header.

"Host" field cannot use ip address, or get ```Server did not reply with a websocket upgrade: Header code: 403 Header reason: Forbidden Address: 3.85.70.150:443```. It is ok for autobahn because the the autobahn server configuration is using ip address and not using hostname.

host address: need to be resolved using e.g. `getHostByName` / `getAddrInfo`
host port: use default 443 for wss and 80 for ws if the port is not specified.

**Comment by dryajov** [comment]
I'm not sure if we should handle DNS resolution at the library level. There are way too many complications and hardly a one way fits all approach (see https://github.com/status-im/nim-libp2p/pull/580 for more context). 

Chronos already exposes a `resolveTAddress` that calls `getAddrInfo` underneath, this does DNS resolutions. We do need to allow the caller to set the hostname when calling `ws.connect`. 

Changing the underlying behaviour is trivial, but it does introduce corner cases that I rather not deal with in the library itself.

A simple workaround is to call (of course we need to allow setting the hostname):

(pseudocode)

```nim
let addrs = resolveTAddress("mainnet.infura.io", 443.Port)
for a in addrs:
  let ws = await WebSocket.connect(
     a,
     path = "/ws/v3/infura-id"),
     hostname = "mainnet.infura.io")
```

**Comment by dryajov** [comment]
@Menduist would like to hear your opinion on this too.

**Comment by Menduist** [comment]
Yes, I've been holding off on the DNS in libp2p specially for this (and certs validation)

I think your pseudo code api is good, though you could provide a simple wrapper which calls resolveTAddress with a warning for applications that do not care about blocking resolve (like nimbus)

**Comment by dryajov** [comment]
After considering this again, I added support for DNS resolution in #81. One reason is that it's fairly common for websocket libraries support DNS out of the box. In the process I realized that the client `connect` api wasn't very consistent and cleaned it up a bit.
