### ISSUE TITLE
Nimbus livelock in recvMsg

### ISSUE THREAD

**Issue by Menduist** [status-im/nim-websock#94]
https://gist.github.com/stefantalpalaru/311ea3e48f104250c6c3dbc4ee0b3718

**Comment by zah** [comment]
Also filed separately here:
https://github.com/status-im/nimbus-eth2/issues/3130

**Comment by Menduist** [comment]
Update: waku also hit this, see https://github.com/status-im/infra-nim-waku/issues/50

Decided to go the fuzzing route with success, I can reliably reproduce the issue.
https://github.com/status-im/nim-chronos/blob/875d7d8e6ef0803ae1c331dbf76b1981b0caeb15/chronos/streams/asyncstream.nim#L473-L478

This procedure seems to return 0 in some case, which goes against it's description, and is not handled properly by nim-websock
I'll now investigate if it's a chronos or nim-websock issue

**Comment by arnetheduck** [comment]
> This procedure seems to return 0 in some case, which goes against it's description,

presumably it would return 0 on a closed connection, no?

**Comment by Menduist** [comment]
Yes, I (and probably whoever wrote this bit) expected an exception instead
However, in reality it depends on what's wrapped by the AsyncStream
